### ISSUE TITLE
Moonsnare and Aetheric tools don't seem to engage autorepair

### ISSUE THREAD

**Issue by gchpaco** [Sirplop/AetherworksRefracted#2]
So I made myself some moonsnare jars and aetheric tools, and while the collector *is* gathering impure aetherium sludge at night (so that part's working fine) even when I dial the self repair up to 10 on both, I've never seen moonsnare jars or aetheric tools self heal / generate ember.

**Comment by gchpaco** [comment]
1.20.1, Forge 47.2.32, Aetherworks 1.0.4, Embers Rekindled 1.3.9

**Comment by Sirplop** [comment]
I am unable to reproduce the issue - are you standing under any blocks? You must have a direct line of sight to the sky from where you're standing.

**Comment by gchpaco** [comment]
Certainly shouldn't be, and the moonlight collector is working which suggests that it, at least, is passing its collection.  I'll try in the end.

**Comment by Sirplop** [comment]
I do not believe the aetheric tool repair or moonsnare jars work in the End. Might implement that functionality.

**Comment by Sirplop** [comment]
I have found the issue: both moonlight functions are checking against the day timer and not against the time of day (day timer goes above 24000, time of day wraps around). This issue is fixed, additional functionality for other dimensions that should also trigger the moonlight repair will come shortly, as well. (Moonlight Harvester uses a different function to check the time of day, which is why it is unaffected)
