### ISSUE TITLE
Crossbow of the Stars Befall doesn't respect warden immunity

### ISSUE THREAD

**Issue by gchpaco** [Sirplop/AetherworksRefracted#3]
I'm not sure how much of this is that particular crossbow and how much is the diffraction barrel I have on it, but when wardens emerge from the earth they are normally invulnerable.  But I can unload on him, and with my current crossbow if he's spawning next to me I can kill him before he emerges.

**Comment by gchpaco** [comment]
It just doesn't seem to respect invulnerability periods in general, I think; withers spawning in get murdered, withers during phase 2 when they're supposed to be immune to ranged damage get murdered.  Checking with the other crossbow, same sort of deal, it's just not as extreme because it doesn't ramp up damage like Stars Befall does; can hurt the wither during spawn animations, can hurt the wither when it's projectile immune.  The blazing ray at least does not have these properties, so maybe you can crib from RCX's code?

**Comment by Sirplop** [comment]
The crossbows were using the wrong damage type (they were using the damage type for Moongaze, which bypasses invulnerability) instead of regular ember damage. The Crossbow of the Stars Befall, specifically, also wasn't checking if it actually hurt the entity it hit before setting the entity's hurt duration, making them look like they were damaged. Fix will be out in 1.0.5.
